### ISSUE TITLE
[Bug] in mid sentence single shift press (in gesture typing) doesn't capitalize the first letter for that word

### ISSUE THREAD

**Issue by techxidize** [AnySoftKeyboard/AnySoftKeyboard#2288] opened 2020-05-22 06:11 UTC
Title: in mid sentence single shift press (in gesture typing) doesn't capitalize the first letter for that word

But, double shift (all caps) works fine (in gesture typing) (mid sentence)

[ Layout I use : first one, English QWERTY ]

**Comment by Jackalaq** [comment] 2020-05-23 21:50
Near duplicate of these open bug reports:

Capitalization fails when swiping
#1821 opened on 16 Aug 2019 by smnthermes

enhancement: capitalize word when pressing shift
#1769 opened on 13 Jul 2019 by Linkinsoldier
6 comments

The older bug suggests a strange 'shift affects previous word' behavior.
I strongly suggest short shift before gesturing a word should capitalise next character (standard behavior). Alternatively, if text is selected, then Shift press should offer different capitalising transformation of selected text:
lower,  Sentence case, ALL CAPS, Initial Letters, DiCtIoNaRy sPeCiFiC
Double click Shift capitalises all following characters (CAPS LOCK)
Thanks!

**Comment by Jonta** [comment] 2021-09-07 18:56
Closed as duplicate of e.g. https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1953

**Closed by Jonta** 2021-09-07 18:56 UTC
Labels: bug, duplicate
