### ISSUE TITLE
No capitalized words in next word prediction.

### ISSUE THREAD

**Issue by Kratsac** [AnySoftKeyboard/AnySoftKeyboard#706] opened 2016-09-15 17:46 UTC
### Steps to reproduce
1. Install German language pack from play store.
2. Even manually saved nouns (all have to be capitalized) will have changed when displayed as a next word suggestion.
### Expected behaviour

All nouns and names should have an capitalized first letter.
### Actual behaviour

Tell us what happens instead

Android 5.1.1

**Comment by qfvldaa2xn** [comment] 2017-01-28 13:52
I installed the new version of the German language pack from F-Droid 2.0.1.
And I can confirm it only happens with the next word prediction. When I start typing the first letter, then it predicts the capitalized word.

# For example "Guten Tag":
I used already before "Guten Tag", then the second time I type **Gu** and right afterwards I choose the prediction "Guten" then I see the next word prediction "tag" with lower cases instead of upper cases.

When I ignore the next word prediction and keep on typing **ta** (lower case) then I see the prediction "Tag" with capital T, which is correct.

**Comment by trevor87** [comment] 2017-07-20 15:50
Same problem here in 1.8.1241 version-code 2566

**Comment by matthias-g** [comment] 2017-09-18 15:53
The problem is that the words for the next words prediction are being [stored in lowercase](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java#L216) only.
Is there a reason not to change this?

**Comment by qfvldaa2xn** [comment] 2017-11-02 18:06
Seems that the code that @matthias-g refers to [takes](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java#L58) the `Locale.getDefault()`, which is the system locale right?

So if I [understand it correctly](https://beginnersbook.com/2013/12/java-string-tolowercase-method-example/), then using AnySoftKeyboard with German system locale should store the next word suggestion **not** in lowercase and e.g. English system locale in lowercase.

But anyways, as many people with a non German system locale use the German keyboard it should be changed.

**Comment by Kratsac** [comment] 2018-03-07 07:46
Still the same problem in 1.9.1117. No capitalized words from next word prediction. Is there any chance to solve this in the future? Otherwise, it would remain useless to me. 🙄

**Comment by qfvldaa2xn** [comment] 2018-03-07 09:14
Yes, indeed this bug is still not resolved.
Can anyone try if changing https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java#L56 to a German locale solves the problem?

(Sorry I am not at home these days, so I don't have a machine here to compile the code at the moment.)

**Comment by Kratsac** [comment] 2018-06-09 11:01
Is there any chance this has been solved in the newest version? I am still hoping it's going to be.

**Comment by Kratsac** [comment] 2018-10-21 11:38
Please, can somebody solve it? Thanks a lot!

**Comment by jwsp1** [comment] 2019-12-17 18:13
Same problem over here. Very annoying bug...

**Comment by jwsp1** [comment] 2019-12-17 18:15
Cc #1322

**Comment by ArenaL5** [comment] 2019-12-27 15:41
This bug was accidentally forgotten and reported three times. There is a tentative fix now, but it hasn't been reviewed yet.

Please check #1914.

**Comment by Jonta** [comment] 2021-09-07 19:03
This seems like it's fixed. I can write "Guten Tag" with swiping gestures

Closing

**Closed by Jonta** 2021-09-07 19:03 UTC
