### ISSUE TITLE
Fast typing moves keyboard cursor back a character most of the times

### ISSUE THREAD

**Issue by RenatoLopes771** [AnySoftKeyboard/AnySoftKeyboard#1875] opened 2019-11-12 03:04 UTC
It's so annoying. It makes me intentionally type slow so the thing doesn't make this kind of behaviour. Please fix.

(What I mean by the title is it would be the equivalent of pressing that arrow key at the top withouth finishing typing a word)

**Comment by ArenaL5** [comment] 2019-11-24 13:08
Duplicate of #1290.

**Comment by ArenaL5** [comment] 2019-12-02 17:40
I can verify this bug, and I believe I've found the conditions that trigger it. If I'm right, I'd really like you to check this bug after PR #1893 is corrected and merged, as I just removed a function which might have bene making your bug worse.

For me, this bug happens only if:
- word prediction is enabled, and the word I'm typing is underlined.
- I press on two keys (let's say, first A, then S) before releasing any.
- I release key S before releasing key A, outputting "as" but making the cursor advance only one letter instead of two.

If someone can verify or deny these conditions, it would greatly help to eventually fix this bug. 

(For the moment, if you want to keep using AnySoftKeyboard while this bug is not fixed, try closing the suggestions bar or disabling suggestions altogether.)

**Comment by YoshK** [comment] 2020-01-21 12:13
Hey,
I have the same issue on a Huawei P20 pro 9.1
Any workaround has been found?

**Comment by menny** [comment] 2020-01-21 13:19
Are you seeing this with the latest release?

**Comment by YoshK** [comment] 2020-01-21 17:03
The last release accessible through F-Droid at least: 1.10.1096

**Comment by dkathmann** [comment] 2020-01-28 20:41
> Are you seeing this with the latest release?

I'm on 1.10.1096 (Play Store) and the bug still occurs.

**Comment by karpad3** [comment] 2020-02-13 16:00
I'm on 1.10.1096 as well and the bug still occurs. It's like that in the last few months.
I'm using Xiaomi Redmi Note 5 with Android 9.

**Comment by menny** [comment] 2020-02-13 20:17
I can not reproduce this, but I have other devices. Could you provide a video capture?

**Comment by dkathmann** [comment] 2020-02-14 18:23
@menny [video capture download](https://send.firefox.com/download/fe56c7118b3f328c/#D4Q2JF4HCQ46M6Bmm6bokw)

**Comment by technOdin** [comment] 2020-02-23 00:56
I have the same issue on my Huawei P20 Pro.

**Comment by menny** [comment] 2020-02-23 03:08
@dkathmann the link expired. Can you send again?

**Comment by dkathmann** [comment] 2020-02-23 18:07
@menny [reupload](https://send.firefox.com/download/3bfa9675e8861851/#FTagEmbPKbn1uqC9vKZSSQ)

**Comment by vocux** [comment] 2020-03-02 20:43
I have this exact same problem using 1.10.1109 on an Honor 8x. It seems to me that this behaviour has gotten much worse since my last update a few weeks ago (don't know the version number unfortunately), before that it occurred rarely. Now however I have to retype 1 out of 3 words and that, needless to say, makes ASK almost unusable :/

**Comment by technOdin** [comment] 2020-03-14 19:16
@menny any update on this?  My Huawei P20 Pro has become a major test of patience when using this keyboard now.  I would like to keep using ASK, but if this apparent issue with Huawei devies cannot be resolved I will have to look to other keyboard apps.  I do appreciate your effort with this - save for this issue, the app is wonderful.

**Comment by menny** [comment] 2020-03-14 22:24
We have two possible fixes for this. Please understand that we find this issue very hard to reproduce and to find the cause.

We will publish a debug version here, in this issue, with the possible fixes. Will you be able to test them out?

**Comment by technOdin** [comment] 2020-03-15 05:42
No worries, I totally get it.  This is an odd bug that appears to only happen with Huawei devises, so I bet it's a tricky one to isolate.  Again, I appreciate your efforts.

I'd be happy to test the patch or debug version when ready.  Let me know when you have it ready and I'll give it a go.

**Comment by vocux** [comment] 2020-03-15 20:07
I will also gladly help and test the debug version :) Thank you so much for looking into this!

**Comment by menny** [comment] 2020-03-16 00:45
Please install the attached APK.
This APK can not upgrade the production/beta app (it uses a different signature), this means that you need to uninstall the version you have now, and install this.

Also, since it uses a different signature, it means that you will not get auto-updates while this version is installed.

[ime-app-1.apk.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/4335573/ime-app-1.apk.zip)

**Comment by vocux** [comment] 2020-03-16 01:56
@menny Thanks for uploading! I just gave it a try. Unfortunately the issue persists without any changes using this debug version on my device.

**Comment by technOdin** [comment] 2020-03-16 02:39
@menny Thanks for sending this, but it didn't work for me either, the issue still seems to persist.  I don't know if it helps, but the issue does seem to be slightly better after this install, and it also seemed to maybe be worse the longer I used it before.  That could just be my imagination though.

**Comment by menny** [comment] 2020-03-16 03:20
This is another possible fix:

[ime-app-1.apk.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/4335886/ime-app-1.apk.zip)

**Comment by technOdin** [comment] 2020-03-16 03:41
@menny That did it!  Or at least after a few uses the issue seems to be gone.  I'll let you know in the next day or two after I use it more if it comes back.  Thank you!

**Comment by vocux** [comment] 2020-03-16 11:05
@menny I tried your second version as well. At first I was euphoric because similar to @technOdin 's experience it seemed like it now occured rarely when writing "real" text, however sometimes it still happened and by typing gibberish I could always reliably reproduce it. Please see this video: 
https://www.dropbox.com/s/8xxo6y59qrh4h5l/ASK_English.mp4?dl=0

Then however after writing a few messages in German I noticed that using the German keyboard this issue is still as bad as before. I don't know if the German language pack is to blame for this, does it need to be fixed separately? See video:
https://www.dropbox.com/s/6czpdf8kggssbf9/ASK_German.mp4?dl=0

**Comment by emilkroll** [comment] 2020-03-19 08:00
I experience this issue too, on a Hauwei p9.
I very happy with Anysoft, though this issue is rather bothering. 
Any chance the above fixes will be incorporated (if working) in the next update of the software?
cheers

**Comment by technOdin** [comment] 2020-03-19 13:53
@menny I have been using this version for the last few days and while the issue is significantly reduced, it is still present on my Huawei P20 Pro.

**Comment by menny** [comment] 2020-03-19 17:14
Is this happening in any app?

**Comment by vocux** [comment] 2020-03-19 17:20
Happens in every app (is that what you meant)?

**Comment by fahadmaqsood** [comment] 2020-04-01 16:59
I actually found the problem... This code in the file "AnySoftKeyboardSuggestions.java" is causing it:

(Line: 556-560)

>                 int cursorPosition = newSelEnd - candidatesStart;
>                 if (mWord.setCursorPosition(cursorPosition)) {
>                     Logger.d(
>                             TAG, "onUpdateSelection: cursor moving inside the predicting word");
>                 }

When I comment that out... the keyboard works properly... I see no cursor jumping at all.

**Comment by technOdin** [comment] 2020-04-10 14:49
@menny were you able to reproduce the success fahadmaqsood noted?  The version you sent previously seems to be slowly getting worse, although it is still much better than the previous standard version.

**Comment by fahadmaqsood** [comment] 2020-04-10 15:14
@technOdin I can assure you and @menny that I haven't encountered this problem even a single time after I commented that part of code.

**Comment by technOdin** [comment] 2020-04-10 15:46
OK, that sounds really promising, but I'm not sure how to get into the javascript of the app on my phone.  @menny are you able to roll this out in the next release?

**Comment by Marjolain** [comment] 2020-04-19 13:21
Hello,
I'va got exactly the same issue on Lineagos 14.1 on moto G4 (Motorola). (AZERTY french pack)
It's weird because it's new and on my other moto G4 lineageos, it's not append. 
The keyboard is OK but with this bug it's not usable.
@fahadmaqsood your correction is in the code, not in the app phone, so we need to /make the .apk?
Thanks forme your time ans your work.

**Comment by fahadmaqsood** [comment] 2020-04-19 16:24
@menny would be able to generate an apk file. but that code is there for some reason and there will be side-effects if it is removed. I think @menny should think of a better way to do what he was trying to do by that code so that you don't face the cursor jumping problem. 

I am creating an android keyboard based on AnySoftKeyboard's code. I have removed that part of code and I notice the side-effect sometimes but it is not that annoying when compared to cursor jumping problem and I think majority of the people will never notice that bug that would be caused by the removal of that code.

**Comment by menny** [comment] 2020-05-20 01:52
could you try https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/698259503/artifacts/6692894
I've made a large refactor, which may have speed up things. Or completely slowed them....

**Comment by YoshK** [comment] 2020-05-20 06:58
Hi,

I download the latest on playstore:

Version 1.10.1096, version-code 6266.

Issue is still present sadly. Anything special i should try to repro to help you out ?

Thanks for your work

Cheers !

-------- Message d'origine --------

**Comment by YoshK** [comment] 2020-05-20 07:04
Actually, it doesn't help on the app 'signal' but it seems to work on fb 'messenger' !

However, both apps crashed at some point while typing so you might want to check that.

-------- Message d'origine --------

**Comment by vocux** [comment] 2020-06-01 11:57
> 
> 
> could you try https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/698259503/artifacts/6692894
> I've made a large refactor, which may have speed up things. Or completely slowed them....

Many thanks for your latest apk. I've tried it, and I can still reproduce the cursor jumping, however in dialy app usage it isn't as bad as before. However there is a terrible bug with this version, sometimes the last letter of the word I just typed gets deleted? Just as annoying as the cursor jumping... I can make a video if you want.

I've actually been using this
> 
> 
> This is another possible fix:
> 
> [ime-app-1.apk.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/4335886/ime-app-1.apk.zip)

debug version (from Mar 16) for the last weeks... Any other version was unusable for me.

**Comment by kdueckmann** [comment] 2020-06-02 20:46
I have had this issue for some time as well (on my Huawei Mate 10 Pro) and have found a setting that solves the problem for me.
In the UI-settings -> Keyboardeffects and experience -> Animations (please excuse any imprecisions in the naming, I am using the app in German), I have selected "None".

(Previously I had already perceived that the problem is also solved by turning off the suggestions, but was not willing to sacrifice those, but I can definitely live without the letter pop-ups)

**Comment by vocux** [comment] 2020-06-03 20:44
> 
> 
> In the UI-settings -> Keyboardeffects and experience -> Animations (please excuse any imprecisions in the naming, I am using the app in German), I have selected "None".
> 
> 

Awesome, thanks for this tip! Made the problem disappear.

**Comment by emilkroll** [comment] 2020-06-11 02:20
This is amazing. I've been really happy with the app, but the cursor bug was annoying.
NOW it fixed!

(Hauwei P9 Lite)

**Comment by menny** [comment] 2020-06-14 04:03
it's the animations!!? that's the issue?

**Comment by technOdin** [comment] 2020-06-14 05:14
I turned the animations off on my Huawei P20 Pro and it seemed to help a bit, but the cursor still moves back while typing occasionally.  I use ASK on my work Samsung Galaxy S10+ and it works like a dream, but this stupid Huawei still glitches.  It's a real irritant, and an absolute pain.  Never buy Huawei, ever - absolute garbage.  They won't even give us boot loader unlock codes anymore so I can flash a different ROM.  So pissed off.  

I appreciate all your efforts menny, but sadly the issue persists for me on the P20 Pro.

**Comment by vocux** [comment] 2020-06-25 13:52
I really don't know... Maybe the animations are interfering with another component and that's what's causing the issue. On my Honor 8x I don't have any issues anymore and can't even reproduce it with animations turned off.

**Comment by underlineGalaxy** [comment] 2020-06-27 01:32
After a few weeks of testing, I can testify that disabling the animations definitely solves the issue. Maybe they shoud come disabled by default or at least until a fix is found?

Another thing to note that is I noticed this bug more when the keyboard was "laggy" (like rendering at 30fps). I presume this happens when the phone is using lot of CPU, as I noticed this happen mostly on reddit and typing youtube comments. After I did this workaround, even if the keyboard was laggy the issue **never** happened again.

**Comment by PrSunflower** [comment] 2020-08-26 12:38
Disabling the animations definitely helps, thank you for the hint!

Since 5 days I have been using ASK with animations disabled and I have never had the issue again, whereas with animations on the problem happened multiple times a day.

(Nokia 7.2 with Android 10)

**Comment by menny** [comment] 2020-11-09 03:22
would you mind trying out https://github.com/AnySoftKeyboard/AnySoftKeyboard/suites/1470313885/artifacts/25293257

**Comment by menny** [comment] 2020-11-09 13:04
To be able to go back to the latest stable version:

1. Backup settings in AnySoftKeyboard
1. uninstall
1. download, unzip, and install the APK from the link
1. follow the setup process
1. restore from the previously saved backup file.
1. Verify that everything is good.

Note: Keeping this version will not allow auto-updates from Google Play Store.

if you want to go back to the previous stable version:

1. Uninstall the test version
1. Install AnySoftKeyboard from Play Store
1. Follow the setup process.
1. restore from the previously saved backup file

**Comment by menny** [comment] 2020-11-10 15:48
seems to be fixed: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2320

**Closed by menny** 2020-11-10 15:48 UTC
