### ISSUE TITLE
It is listed under "Battery draining apps" for constantly running in background, and a battery usage warning appears.

### ISSUE THREAD

**Issue by poikilos** [AnySoftKeyboard/AnySoftKeyboard#1816] opened 2019-08-12 20:09 UTC
App version: 1.10.606

### Steps to reproduce
1. Install
2. Wait

### Expected behaviour
Application should instruct you whether or not it will work properly if disabled for power saving, or preferably handle the situation itself. I don't know whether AnySoftKeyboard can be implemented without running constantly in the background or not. I didn't have this problem with other keyboards, but I also don't think I had this problem when I first installed AnySoftKeyboard (I could be wrong, because I don't remember). Therefore, the issue may be with AnySoftKeyboard or that my updated Android version is monitoring background apps differently than before.

### Actual behaviour
I keep getting a popup from the OS saying AnySoftKeyboard is a battery draining app. If I click the message, it says: (under a "Battery draining apps" heading):
> Some apps constantly run in the background. To save battery, restrict these apps in the background or uninstall them.

- Presumably the message will go away if I click the message, then in the "Diagnose" window I click "Restrict," but I don't know whether that will cause  AnySoftKeyboard to stop functioning.
- Presumably the message will go away if I choose to "exclude...from power saving" but I don't want to do that until I'm sure it isn't wasteful to exclude it.

**Android OS version:**
- **9**
- Android security patch level: June 1, 2019
- Kernel version: 4.9.112
- Build number: PKQ1.190202.001
- Software version: V405UA20e

**Device manufacturer and model:**
LG V40 ThinQ

**List of installed add-ons (like languages, or themes):**
- Colmak (set as current language)

**Comment by AnXh3L0** [comment] 2019-12-13 09:36
Hi there @poikilos, this is because of some changed on Android Oreo and above but there's nothing to be worried about. That's a generic message that will show for all apps that tend to run in the background, and no, I don't think ASK or any other keyboard can be implemented to not run in the background all the time.

Unless the battery usage monitor shows ASK as a battery drainer, you shouldn't be worried.

**Comment by poikilos** [comment] 2019-12-14 02:50
Ok, I was pretty sure the battery wasn't being drained. The message just keeps re-appearing. I  suppose there is no way to suppress the message then. That's unfortunate if not.

**Comment by poikilos** [comment] 2019-12-14 02:53
Ok, thanks. I excluded it from power saving (Settings, General, Battery, Power saving exclusions), so I'll see if the message goes away.

**Comment by AnXh3L0** [comment] 2019-12-14 21:53
Closing this issue as not a bug because it is related to Android itself.

**Closed by AnXh3L0** 2019-12-14 21:53 UTC
