### ISSUE TITLE
Keyboard does not initialize on boot. User could get stuck at lockscreen forever

### ISSUE THREAD

**Issue by pablojimpas** [AnySoftKeyboard/AnySoftKeyboard#2525] opened 2020-11-08 10:41 UTC
### Steps to reproduce
1. Set up AnySoftKeyboard as the default and only keyboard
2. Set up "password" protection, without PIN nor pattern
3. Reboot the device (or shutdown and power on) and you will be stuck in the lockscreen prompted to enter the password but without keyboard

### Expected behaviour
Start at boot time to allow the user to enter the password and unlock the device

### Actual behaviour
The keyboard does not appear in the lockscreen if you reboot or have just powered on the device

**Android OS version:** Android 10

**Device manufacturer and model:** Motorola Moto One Vision

**List of installed add-ons (like languages, or themes):** Spanish language pack

**Comment by pablojimpas** [comment] 2020-11-08 10:45
Maybe related to #2445

**Comment by menny** [comment] 2020-11-08 14:39
Does it revert to the stock keyboard?

**Comment by pablojimpas** [comment] 2020-11-08 15:15
I guess it will fallback to other keyboard in case you have it, but not in my case since I disabled Gboard

**Comment by menny** [comment] 2020-11-08 19:40
How did you avert a bootloop then?

**Comment by pablojimpas** [comment] 2020-11-08 19:55
I tried rebooting in safe mode and connecting to adb but I had developer mode disabled...so I ended up doing a factory reset after a little bit of research, maybe I would have found a solution if I search more but I thought that resetting was faster :disappointed:

**Comment by moonshaadow** [comment] 2020-12-07 20:50
I can confirm  that I have to activate ask at every boot (last release of ASK, Android 8.1, alcatel 5033d, french pack)
ASK is my default keyboard, and having   another installed keyboard change nothing.

**Comment by sachinn360** [comment] 2020-12-29 07:15
> Does it revert to the stock keyboard?

It Does revert to stock keyboard if enabled.

**Comment by dario617** [comment] 2021-01-31 14:58
This happened to me once, I had to plug a desktop keyboard to unlock my phone without losing any data. I think this is an issue with android itself 🙄

**Comment by menny** [comment] 2021-01-31 16:38
I would love to get some insides into this, some kind of debug report or `adb logcat` would go a long way

**Comment by Balu-SomeNumbers** [comment] 2021-07-10 01:32
Happened to me yesterday 😭
I installed Anysoft keyboard in the morning and gave it the necessary permissions. After that, I switched back to using Gboard cause the was more comfortable for me.
But when I restarted the phone in the evening, the keyboard didn't open up to type the password.

Since I'm on Android 10, ideally only Gboard would be able to show up on the lock screen irrespective of other keyboards installed. But after installing AnySoft, neither of the keyboards are helping me out

Device: Xiaomi Mi A2
OS: Android 10 (stock)
Beta Version Enabled: I did sign up for it, but I don't know if I received the update before the incident

Someone help me out, I don't want to reset my phone 😭

**Comment by dario617** [comment] 2021-07-10 02:14
> Happened to me yesterday 😭

Hey I had to buy a USB dongle to plug in my computer keyboard. I waited a couple days for the delivery but I got in :)

**Comment by Balu-SomeNumbers** [comment] 2021-07-10 07:04
> > Happened to me yesterday 😭
> 
> Hey I had to buy a USB dongle to plug in my computer keyboard. I waited a couple days for the delivery but I got in :)

I tried it right now. It didn't work...
It looks like we had to change the developer settings before hand to permit the connection....

**Comment by menny** [comment] 2021-07-12 15:54
I don't understand the issue, to tell you the truth. Are you saying that the OS is not showing _any_ on-screen keyboard when asking for the device password?

**Comment by dario617** [comment] 2021-07-12 16:02
The issue is that the OS doesn't allow the keyboard to load on startup because it doesn't load external apps. So for example when I disabled my GBoard Keyboard (so I could use AnySoft) I got locked out of my smartphone. 

I even got a warning after disabling GBoard but I dismissed it 😅

**Comment by ItsIgnacioPortal** [comment] 2022-10-18 14:11
This is a duplicate of #2445

**Comment by menny** [comment] 2022-10-18 21:46
true. this is fixed now.

**Closed by menny** 2022-10-18 21:46 UTC
Labels: duplicate
