### ISSUE TITLE
[bug] not possible to add one letter word 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [AnySoftKeyboard/AnySoftKeyboard#1849] opened 2019-09-16 08:30 UTC
It's not possible to add one letter word directly by double taping on it. Still possible in option, edit dictionary.

**Comment by jwsp1** [comment] 2019-10-29 20:26
This is the same behavior as when trying to add a word while incognito mode is enabled. It also doesn't work then, regardless how many characters.

Referring #1738

**Comment by ArenaL5** [comment] 2019-12-18 02:06
Duplicate of #1747.

**Closed** 2019-12-19 18:02 UTC
