### ISSUE TITLE
New Line in SMS instead of sending it

### ISSUE THREAD

**Issue by Mannshoch** [AnySoftKeyboard/AnySoftKeyboard#973] opened 2017-04-17 07:30 UTC
Device: (Fairphone 2, Android 5.1)
In SMS My Phone send SMS if I press Enter instead do a new line. I'm also not able to change this behavior in settings. Also Shift-Enter do not change it.

**Comment by ArenaL5** [comment] 2019-11-06 01:11
Duplicate of #1056.

**Closed** 2019-11-06 02:32 UTC
