### ISSUE TITLE
Vibration

### ISSUE THREAD

**Issue by Setuneh** [AnySoftKeyboard/AnySoftKeyboard#3097] opened 2021-12-04 22:56 UTC
### Steps to reproduce
1. No vibration when typing
2.
3.

### Expected behaviour
stop vibration when typing

### Actual behaviour
ita vibrating when i type with ask

**Android OS version:**11

**Device manufacturer and model:**galaxy s10+

**List of installed add-ons (like languages, or themes):**

**Comment by Ghostbird** [comment] 2021-12-05 21:22
Seems like a duplicate of #3096

**Comment by menny** [comment] 2022-01-02 14:16
@Setuneh , sis you try to disable vibration as @Ghostbird suggested?

**Comment by Setuneh** [comment] 2022-01-02 16:43
Yes, thank you!

Menny Even Danan ***@***.***> ezt írta (időpont: 2022. jan.
2., Vas 15:16):

**Closed** 2022-01-05 19:52 UTC
