### ISSUE TITLE
Wrong emoji size in picker

### ISSUE THREAD

**Issue by Steinhagen** [AnySoftKeyboard/AnySoftKeyboard#2792] opened 2021-03-20 06:18 UTC
### Steps to reproduce
1. Open the emoticons picker

### Expected behaviour
All emojis should have the same size in the selection window.

### Actual behaviour
The emojis size differ (probably because some of them are missing a size)

**Android OS version:**
Android 8

**Device manufacturer and model:**
Galaxy S8+

**List of installed add-ons (like languages, or themes):**
None

**Comment by Steinhagen** [comment] 2021-03-20 06:19
![20210320_080935.jpg](https://user-images.githubusercontent.com/4029937/111861187-055ae300-8955-11eb-86d1-f0d8fe209bb9.jpg)

**Comment by Jonta** [comment] 2021-03-25 07:23
Duplicate of https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1753

**Comment by Steinhagen** [comment] 2021-03-25 21:52
Closing this bug since the problem was already reported.

**Closed** 2021-03-26 10:38 UTC
