### ISSUE TITLE
Feature request: In german language is missing the § (for paragraph)

### ISSUE THREAD

**Issue by fronki** [AnySoftKeyboard/AnySoftKeyboard#1925] opened 2019-12-20 08:08 UTC
I can't find the sign § in the german language pack for android.

It could be as popup behind the "s".

**Comment by ArenaL5** [comment] 2019-12-27 12:17
Duplicate of #1853. It's easy to fix, but the staff is currently busy with Christmas and other problems on the code.

If you're using AnySoftKeyboard BETA, you may find this symbol behind the asterisk on the number keyboard, no matter what layout you choose. I'm not sure if this is the case on current published version r2.

**Comment by fronki** [comment] 2019-12-27 14:19
OK. I couldn't fond. ButI have a workaround. I usw the  replace finction. For the definiton I use Anleger keyboard.
Kind regards
Frank
--
Frank Wächtler  Freitag, 27 Dezember 2019, 01:17nachm. +01:00 von ArenaL5  notifications@github.com :

**Closed** 2020-03-24 23:35 UTC
