### ISSUE TITLE
Custom backup location

### ISSUE THREAD

**Issue by lawson85** [AnySoftKeyboard/AnySoftKeyboard#2728] opened 2021-02-26 11:31 UTC
You are saving the backup to a root only location so it cannot be moved to other devices or please at least add a backup share option

**Comment by siccovansas** [comment] 2021-03-06 10:30
It seems this feature was already discussed in https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1780 and merged in pull request https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2365. Apparently AnySoftKeyboard doesn't release new versions often (once a year), so we'll have to wait for the next release.

**Comment by Jonta** [comment] 2021-09-04 12:35
Closing as duplicate of #2815

**Closed by Jonta** 2021-09-04 12:35 UTC
