### ISSUE TITLE
Cannot Create Android/data/com.merry.android.anysoftkeyboard/files/ Folder on Android 11

### ISSUE THREAD

**Issue by landry314** [AnySoftKeyboard/AnySoftKeyboard#2797] opened 2021-03-22 18:58 UTC
Backing up settings file on Android 11 to the default folder in <Android/data/com.merry.android.anysoftkeyboard/files/> fails when the folder does not exist already.

This is likely due to the Android 11 file permission being "Allow access to media only".

I've seen this problem in many apps due to the way permission handling has changed recently. The permission needs to be changed to "Allow management of all files" or something else which allows access to the app's external storage.

Using LineageOS 18.1 (Android 11) on a Pixel 3.

**Comment by landry314** [comment] 2021-03-22 19:01
Looking into the details of the permissions I noticed WRITE_EXTERNAL_STORAGE is allowed. I'm not sure why it fails.

**Comment by leonp5** [comment] 2022-07-31 07:23
Same Problem here :-/

**Comment by tb06** [comment] 2022-12-18 22:34
Hello:

On my side, since I installed Android 11, exporting in the default folder seems to work well but it's the only operation that works:

- I cannot export to another folder: I get an error message "Failure to access storage folder" and an empty XML file is created
- I cannot import anymore because the only folder that seems to work is the default folder and I don't have the right to copy a file inside…

The app is allowed to access all multimedia files but not all the files, as it doesn't ask to.

If you think the issue is different from the previous comments I can create a new case.

Thanks in advance for your help!

**Comment by menny** [comment] 2022-12-23 04:32
This issue was fixed on a pre-release version: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3121

If you have installed AnySoftKeyboard from Google's Play Store, you can sign up for the BETA channel, and you will get this fix. If you have installed from F-Droid, then, sorry, you will need to wait.

**Closed by menny** 2022-12-23 04:32 UTC
Labels: bug
