### ISSUE TITLE
Gestures are unale to minimize (close) keyboard on Android 11

### ISSUE THREAD

**Issue by ElektroVirus** [AnySoftKeyboard/AnySoftKeyboard#2888] opened 2021-06-05 13:29 UTC
### Steps to reproduce
1. Set gesture down (or up, left, right...) for minimizing (hiding) keyboard
2. Swipe down on keyboard
3. Keyboard won't minimize

### Expected behaviour
Keyboard should definitely minimize. 

### Actual behaviour
Nothing. 

**Android OS version:**
It worked fine until yesterday when I updated my Android from LineageOS 17.1 to 18.1.
Reinstalled AnySoftKeyboard, didn't help.
Android 11; LineageOS 18.1

**Device manufacturer and model:**
OnePlus5 A5000

**List of installed add-ons (like languages, or themes):**
Finnish

**Comment by Jonta** [comment] 2021-09-03 16:29
Looks like duplicate of https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2883

**Closed by Jonta** 2021-09-03 16:29 UTC
Labels: bug, duplicate
