### ISSUE TITLE
Polish Language pack is not working!

### ISSUE THREAD

**Issue by sabisab** [AnySoftKeyboard/AnySoftKeyboard#646] opened 2016-05-01 07:36 UTC
### Steps to reproduce
1. install https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.polish
   2.
   3.
### Actual behaviour

The Polish language does not appear in the keyboard's language settings.
The function getExternalAddOns --> queryBroadcastReceivers does not get this broadcastReciever.

**Android OS version:**
5.0
**Device manufacturer and model:**
Samsung note 3

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment] 2016-05-01 12:03
That pack was developed by ogonzuhnina@gmail.com , can you contact that
address?

**Comment by kosciak9** [comment] 2016-08-07 20:04
Is there a template for making own packs available anymore? Found some references to it but Google Code site is 404 for me, at least this one topic.

**Comment by ReportingRaccoon** [comment] 2017-01-24 14:40
Confirmed. It's like not having Polish language at all. Please fix it.

**Comment by ArenaL5** [comment] 2019-11-24 19:49
The ASK team has since released [Menny's Polish for ASK](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.osspolish), which source code appears to be [in the Polish branch](https://github.com/AnySoftKeyboard/LanguagePack/tree/Polish).

It would be convenient to move it to the master branch, but this bug seems no longer relevant.

**Comment by AnXh3L0** [comment] 2019-12-01 15:49
This bug seems to have been fixed, closing the issue.

**Closed** 2019-12-01 15:49 UTC
