### ISSUE TITLE
Landscape mode - display gets confused

### ISSUE THREAD

**Issue by bacizone** [AnySoftKeyboard/AnySoftKeyboard#945] opened 2017-03-24 04:14 UTC
### Steps to reproduce
I write using Anysoftkeyboard in landscape mode 

### Expected behaviour
I can just type without any other characters appearing over the keys.

### Actual behaviour
While typing, parts of the text above appears over the keys at the bottom, see examples:
![image](https://cloud.githubusercontent.com/assets/1449929/24280412/ab6693ac-1050-11e7-82a2-a691acaa8839.png)
![image](https://cloud.githubusercontent.com/assets/1449929/24280416/b3470a8e-1050-11e7-88fb-f49351cebcf0.png)

**Android OS version:**
4.2.1

**Device manufacturer and model:**
Zopo 980

**List of installed add-ons (like languages, or themes):**
Hungarian keyboard is being activated and used

**Comment by menny** [comment] 2017-03-25 02:42
Which app is that?

**Comment by bacizone** [comment] 2017-03-26 08:59
Application called "Tasks".

**Comment by menny** [comment] 2017-04-13 18:31
Can you verify the latest release?

**Comment by bacizone** [comment] 2017-04-14 16:26
Latest version of Anysoftkeyboard as of today
It is much better, however it seems that some parts of the application still appears in the bottom part.
See attached screenshot
![image](https://cloud.githubusercontent.com/assets/1449929/25048992/bb4332d0-213f-11e7-9683-f037a7ccbd99.png)

**Comment by lkelemen** [comment] 2017-04-18 10:33
I also have a landscape.issue. App:whatsapp, os:android 7.0, phone:gal s7. Settings:landscape full screen,  word prediction on. How to get it: go landscape in WhatsApp, start to write, screen OK. Press back key and then touch the input field so ASK is shown again. ASK UI covered with a dark transparent frame  on the right and bottom part.

**Comment by lkelemen** [comment] 2017-04-18 10:34
![screenshot_20170418-131833](https://cloud.githubusercontent.com/assets/11487871/25126688/c3833f4a-243b-11e7-8c4c-07359f1f4957.png)

**Comment by lkelemen** [comment] 2017-04-18 10:35
![screenshot_20170418-131853](https://cloud.githubusercontent.com/assets/11487871/25126705/d06689ba-243b-11e7-887e-3614d1f595ec.png)

**Comment by menny** [comment] 2017-04-20 19:54
Does it happen with all themes?

I just can't reproduce this issue on my devices

**Comment by bacizone** [comment] 2017-04-20 20:10
Black theme, Hungarian keyboard. Much better than previous version, but
sometimes happens, especially when pasting text from the clipboard.
I am on Android 4.2.1

**Comment by bacizone** [comment] 2017-05-18 07:24
Hi 

Anysoftkeyboard with Hungarian keyboard is still producing issues in these apps in Android 4.2.1, rooted: 

- Tasks https://play.google.com/store/apps/details?id=ch.teamtasks.tasks.paid
- Dictionary Hungarian English https://play.google.com/store/apps/details?id=com.bitknights.dict.enghun


![image](https://cloud.githubusercontent.com/assets/1449929/26190777/7b88e352-3bab-11e7-8790-c9078d233d5e.png)

![image](https://cloud.githubusercontent.com/assets/1449929/26190783/841e923c-3bab-11e7-8aa8-0556c5ed81ec.png)

![image](https://cloud.githubusercontent.com/assets/1449929/26190796/94c4a41e-3bab-11e7-84cb-286be958d3c5.png)

![image](https://cloud.githubusercontent.com/assets/1449929/26190802/9c8b4392-3bab-11e7-9960-2366831bf50b.png)

It is hard to find reproducible steps, they happen all the time sporadically.

Can you fix these?

**Comment by bacizone** [comment] 2017-05-18 13:31
I am typing mainly in these apps in landscape mode, plus probably you may also test with Google Keep.

**Comment by AnXh3L0** [comment] 2019-12-02 18:33
I couldn't manage to reproduce this bug. Can you please confirm it still happens for you @bacizone and @lkelemen?

**Comment by bacizone** [comment] 2019-12-02 19:30
hi,

it has been present 2.5 years ago, since then I changed phone, still using
Anysoftkeyboard without problems.
You can close that ticket.

thanks,
bacizone

**Comment by AnXh3L0** [comment] 2019-12-02 20:58
Thanks for replying so fast, closing this issue.

**Closed** 2019-12-02 20:58 UTC

**Comment by lkelemen** [comment] 2019-12-03 06:14
tested on WhatsApp with latest ASK. Works OK
