### ISSUE TITLE
White nav bar

### ISSUE THREAD

**Issue by huehuw** [AnySoftKeyboard/AnySoftKeyboard#2631] opened 2021-01-17 14:34 UTC
### Steps to reproduce
1. Open keyboard  on Samsung phone running android 10 and one UI 2.5
2.
3.

### Expected behaviour
Tell us what should happen
Keyboard should open without white navbar on the bottom, 
### Actual behaviour
Tell us what happens instead
currently  the white nav bar appears even when dark mode is enabled when the keyboard is in use
![Screenshot_20210118-002644_DuckDuckGo](https://user-images.githubusercontent.com/77577934/104846119-b5e04280-5924-11eb-91c0-a50f734bc0c8.jpg)

**Android OS version:**
Android 10
**Device manufacturer and model:**
Samsung note 10 plus 5G
**List of installed add-ons (like languages, or themes):none

**Comment by skelerang** [comment] 2021-01-21 02:43
Have you checked "Draw behind the navigation-bar" option under Effects?

**Comment by skelerang** [comment] 2021-01-21 14:37
Hey, is this a duplicate of #2610

**Comment by huehuw** [comment] 2021-01-21 14:47
Hello  what you sugested worked thankyou. I wasn't aware of that option

**Comment by Jonta** [comment] 2021-09-04 12:57
Closing as duplicate and fixed

**Closed by Jonta** 2021-09-04 12:57 UTC
