### ISSUE TITLE
German/Neo2 Keyboard Layout need the letter ẞ

### ISSUE THREAD

**Issue by MovGP0** [AnySoftKeyboard/AnySoftKeyboard#1041] opened 2017-07-02 16:13 UTC
### Steps to reproduce
1. use the German IBM or German Neo2 keyboard layout 
2. long-press the letter 's'
3. a menu with variants of s appears. 

### Expected behaviour
there should also be the capital sharp ẞ

### Actual behaviour
only the lowercase ß can be selected. 

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by friesenkiwi** [comment] 2017-07-09 18:24
Hi @MovGP0 thank you for your report! :)
The NEO pack is maintained independently at https://github.com/kertase/neo_anysoftkeyboard.
For the German pack, this is a duplicate of https://github.com/AnySoftKeyboard/LanguagePack/issues/69 so this can be closed. (@menny)

**Closed** 2017-07-09 20:41 UTC

**Comment by Blaimi** [comment] 2024-03-28 12:29
@menny : Can you reopen this issue because neo2 is now included upstream and the issue still is there. This may be a no-brainer / low hanging fruit together with #3976

**Comment by Blaimi** [comment] 2024-03-28 12:30
nevermind. ß actually prints ẞ when shift is active ;-)
