### ISSUE TITLE
ASK cannot be found

### ISSUE THREAD

**Issue by fingolfin0** [AnySoftKeyboard/AnySoftKeyboard#2778] opened 2021-03-12 14:02 UTC
### Steps to reproduce
1. Open https://f-droid.org
2. Search "anysoft keyboard"

### Expected behaviour
ASK found

### Actual behaviour
You can find ASK by the name "Classic PC Theme"

**Android OS version:**

**Device manufacturer and model:**

**List of installed add-ons (like languages, or themes):**

**Comment by laurentlbm** [comment] 2021-04-05 17:21
The listing is still there, but for some reason is titled "Turkish for AnySoftKeyboard": https://f-droid.org/packages/com.menny.android.anysoftkeyboard/

I wanted to download the app and iy took me 15 minutes to figure that out...

**Comment by MicroBeast** [comment] 2021-04-26 21:46
On F-Droid; the Main/Original ASK app name change every year for reason I never understand. Last year (for me), it German for AnySoftKeyboard. This year; it Basque for AnySoftKeyboard.

And also; it seem the name "of this year" become different for random people or region (someone said it Turkish for him). I remember ever pass someone have it different on one of Reddit post last year.

**Comment by maximilianovermeyer** [comment] 2021-05-19 17:18
It's a duplicate of  #2737 and  there are linked even more.
Adding these for that they can easily be found once the bug is solved. 
#2103
#2161
#2211
#2469

**Closed** 2021-09-03 17:50 UTC
Labels: duplicate
