### ISSUE TITLE
Extension keyboard is right to left

### ISSUE THREAD

**Issue by il3li** [AnySoftKeyboard/AnySoftKeyboard#535] opened 2015-11-15 13:21 UTC
Hi,

It happens sometimes that an extension keyboard appear right-to-left in portrait mode (see an image below)
![screenshot_2015-11-15-14-49-13](https://cloud.githubusercontent.com/assets/15856890/11168895/8a8d64c2-8b71-11e5-8f54-b26c817aa5b8.png)

**Comment by digi-owl** [comment] 2015-11-17 18:17
Seems to happen when the swipe up is from the right half of the keyboard.

**Comment by menny** [comment] 2016-01-12 04:11
Yes, this is correct - when a popup keyboard is shown, there is a constraint that is checked: the first (highest priority) key in the keyboard should be just above the finger. Since the highest priority is the "1" key and there isn't enough screen space to draw the rest of the keyboard (keys 2->0), the keyboard view flips.

This makes sense in normal popups (long pressing L, for example), but I can see why it doesn't make sense in the extension keyboard.

I'll move this to the backlog.

**Comment by ArenaL5** [comment] 2019-11-15 21:11
I can't reproduce this bug in version 1.10.606 or the latest debug version, even when forcing right-to-left layouts.

I think this bug has been fixed by now.

**Closed** 2019-12-10 15:22 UTC
Labels: bug, enhancement
