### ISSUE TITLE
{request} Settings

### ISSUE THREAD

**Issue by Raul1198** [AnySoftKeyboard/AnySoftKeyboard#1734] opened 2019-05-26 17:53 UTC
can we get the UI and setting a little easier to understand and use, thank you

**Comment by AnXh3L0** [comment] 2019-12-01 13:57
Hey there @Raul1198, we are aware that the UI/UX of the settings is quite difficult to work with and are working to improve it. Closing this for now as it's a duplicate of some other requests.

**Closed by AnXh3L0** 2019-12-01 13:57 UTC
