### ISSUE TITLE
Row with numbers is duplicated

### ISSUE THREAD

**Issue by BurlyMynah** [AnySoftKeyboard/AnySoftKeyboard#1876] opened 2019-11-13 18:52 UTC
### Steps to reproduce
1. Add numbers to the top row
2. Open page with special characters

### Actual behaviour
When numbers are added in the top row, they are duplicated on page with special characters. For example, on gboard, it's done like this: when you open page with special characters the row with the numbers goes away, and the rest rows move a bit

**Android OS version:**
9.0

![Screenshot_20191112_141817](https://user-images.githubusercontent.com/21261661/68794061-4f480080-065f-11ea-9d77-252e51d14be7.png)

**Comment by ArenaL5** [comment] 2019-12-05 23:07
Duplicate of #1429.

Thank you for taking the time to upload the report and sending screenshots, anyways. They're very useful.

**Comment by menny** [comment] 2019-12-06 19:36
Duplicate

**Closed by menny** 2019-12-06 19:36 UTC
Labels: duplicate
