### ISSUE TITLE
Graphics accents and other things ES QWERTY keyboard

### ISSUE THREAD

**Issue by OsvaldoMorinigo** [AnySoftKeyboard/AnySoftKeyboard#1585] opened 2019-01-09 15:00 UTC
### Steps to reproduce
1.Press and hold any vowel

### Expected behaviour
There should be vowels with different variations specially with the  ̃ like ẽ or with the dieresis, that is commonly used in spanish specially in the u, y would be grateful if you make that with all the vowels, i recommend you to make the order like this, accent mark because is the most used, next should be dieresis, and next the  ̃

I would also be grateful if you add some commonly used thing, you can see in the samsung keyboard.

### Actual behaviour
There are only accent mark and there is no the dieresis.

**Android OS version:**
6.0.1
**Device manufacturer and model:**
Samsung SM-G532M
**List of installed add-ons (like languages, or themes):**
Spanish pack dvorak, but it does not matter.

**Comment by ArenaL5** [comment] 2019-11-06 00:42
Duplicate of AnySoftKeyboard/LanguagePack#231.

**Comment by AnXh3L0** [comment] 2019-12-13 09:20
Closed as fixed.

**Comment by PandaFoss** [comment] 2020-03-29 04:08
What change did they apply? I still can't find the `ü` on the Spanish qwerty keyboard...

**Comment by menny** [comment] 2020-03-29 05:48
@martholomew are we missing `ü`?

**Comment by martholomew** [comment] 2020-03-29 05:51
It looks to be there https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/master/addons/languages/spain/pack/src/main/res/xml

**Comment by menny** [comment] 2020-03-29 06:09
Thanks.

@pandafoss We are rolling out a new version at the moment, maybe you don't have the latest yet.

**Closed** 2020-03-29 06:09 UTC

**Comment by PandaFoss** [comment] 2020-03-29 19:04
I have version 1.10.1109 (F-Droid).

**Comment by menny** [comment] 2020-03-29 22:02
I was referring to the Spanish language-pack. Should be version 4.0.1283 or later.

**Comment by PandaFoss** [comment] 2020-03-30 03:14
I just installed the Play Store version and it already appears correctly. The latest version published on F-Droid is from 2018.
Is the app still updating on F-Droid or should I also install it from the Play Store?
Thank you!

**Comment by menny** [comment] 2020-03-30 15:23
it's much much easier for us to update fdroid - it's done automatically by a bot, so it's scalable.
On fdroid, a human needs to do the bump.
actually, you can do that!
