### ISSUE TITLE
Capitalization fails when swiping

### ISSUE THREAD

**Issue by smnthermes** [AnySoftKeyboard/AnySoftKeyboard#1821] opened 2019-08-15 23:29 UTC
### Steps to reproduce
1. Press shift 
2. Swipe a word

### Expected behaviour
The word should start with a capital letter 

### Actual behaviour
The word starts with a non-capital letter 

**Android OS version:**
9
**Device manufacturer and model:**
Motorola Moto G 2015
**List of installed add-ons (like languages, or themes):**
PT-BR

**Comment by TheShanMan** [comment] 2021-02-21 04:46
Yes! Hope this gets fixed soon!

**Comment by dbolton** [comment] 2021-03-27 03:16
See also https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1769

**Comment by Jonta** [comment] 2021-09-07 18:53
Closed as duplicate of an older issue, e.g. https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1953

Trying to find the 1st one. =)

**Closed by Jonta** 2021-09-07 18:53 UTC
