### ISSUE TITLE
Where to define keyboard layout

### ISSUE THREAD

**Issue by poet-man** [AnySoftKeyboard/AnySoftKeyboard#1719] opened 2019-05-07 13:18 UTC
When I log into my online-banking, I have normal keyboard on display, without extra number keys, when filling in my username. Going to password-field however, layout changes to keyboard plus extra number keys, which is great.
How is this defined, when this extra number keys will come up, and when not?
Thanks

**Comment by mihawk90** [comment] 2019-07-18 06:48
This is specified by the website, i.e. which type of input field they are using.

You can also test this in the settings app in the main screen top right menu > tweaks > Developer Tools. There is an "EditText Playground" with every type of input field known to Android. Which of them is used depends on the App Developer or in this case the web developer.

**Comment by ArenaL5** [comment] 2019-11-06 02:43
This is a question, not an actual bug, and it's apparently solved.

Close issue?

**Comment by AnXh3L0** [comment] 2019-12-13 09:20
Closed as not a bug.

**Closed by AnXh3L0** 2019-12-13 09:20 UTC
