### ISSUE TITLE
Word Suggestions Do Not Appear In KISS Launcher When Using AnySoftKeyboard

### ISSUE THREAD

**Issue by connerbw** [AnySoftKeyboard/AnySoftKeyboard#1445] opened 2018-09-03 14:25 UTC
When I use GBoard, word suggestions appear on the KISS Launcher. 

When I use AnySoftKeyboard it does not.

Expected: Word suggestions appear when I use AnySoftKeyboard.

Extra: Same behaviour in Google Play, many other apps. 

## AnySoftKeyboard:

Word Suggestions do not appear in KISS.

![anysoft kiss](https://user-images.githubusercontent.com/812192/44991724-0082df00-af63-11e8-9a5d-f14c12e1e73e.png)
![anysoft chrome](https://user-images.githubusercontent.com/812192/44991725-011b7580-af63-11e8-9ccf-8ca6f0d2db3e.png)

## GBoard

Word Suggestions appear everywhere.

![gboard chrome](https://user-images.githubusercontent.com/812192/44991735-0b3d7400-af63-11e8-8d58-9908588a4eef.png)
![gboard kiss](https://user-images.githubusercontent.com/812192/44991736-0b3d7400-af63-11e8-952f-000fc72ff25b.png)

## Info: 

Latest version of KISS and AnySoftKeyboard from Google Play.
Android version 7.0
Moto G5.
Languages installed: English and French (CA)

**Comment by connerbw** [comment] 2018-09-03 14:26
Related: https://github.com/Neamar/KISS/issues/1055

**Comment by AnXh3L0** [comment] 2019-12-02 18:55
This is the intended behaviour because KISS launcher turns off suggestions, meanwhile other keyboard apps cheat by ignoring the flags. Closing this as not a bug.

**Closed by AnXh3L0** 2019-12-02 18:55 UTC
